// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-0VNG33vvyxLhzoxOztsWNE_g7heh7-Y',
    appId: '1:15491907062:web:6b68d491d72e203a7bdbd7',
    messagingSenderId: '15491907062',
    projectId: 'timetracker-c01c9',
    authDomain: 'timetracker-c01c9.firebaseapp.com',
    storageBucket: 'timetracker-c01c9.appspot.com',
    measurementId: 'G-EKJRTNV3LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiYZSzJKrAoPu5-Ro99H6oifTUBZ4ciuE',
    appId: '1:15491907062:android:fa763abf427e279a7bdbd7',
    messagingSenderId: '15491907062',
    projectId: 'timetracker-c01c9',
    storageBucket: 'timetracker-c01c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAljhr6sB6EwMy_0ZdsM-1zjyXtZmd7fp0',
    appId: '1:15491907062:ios:a19b639653c0db257bdbd7',
    messagingSenderId: '15491907062',
    projectId: 'timetracker-c01c9',
    storageBucket: 'timetracker-c01c9.appspot.com',
    iosClientId: '15491907062-gdjkq3ggdfqu628v9iuojpgsukmdh22o.apps.googleusercontent.com',
    iosBundleId: 'com.mes71.workTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAljhr6sB6EwMy_0ZdsM-1zjyXtZmd7fp0',
    appId: '1:15491907062:ios:a19b639653c0db257bdbd7',
    messagingSenderId: '15491907062',
    projectId: 'timetracker-c01c9',
    storageBucket: 'timetracker-c01c9.appspot.com',
    iosClientId: '15491907062-gdjkq3ggdfqu628v9iuojpgsukmdh22o.apps.googleusercontent.com',
    iosBundleId: 'com.mes71.workTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-0VNG33vvyxLhzoxOztsWNE_g7heh7-Y',
    appId: '1:15491907062:web:ee1bacabaf37fa827bdbd7',
    messagingSenderId: '15491907062',
    projectId: 'timetracker-c01c9',
    authDomain: 'timetracker-c01c9.firebaseapp.com',
    storageBucket: 'timetracker-c01c9.appspot.com',
    measurementId: 'G-NY81H752ME',
  );
}
